name: Typos AI
description: Run typos.ai checks
inputs:
  key:
    description: ai key
    required: true
  run:
    required: false
    default: "1"
    description: Run typos
runs:
  using: composite
  steps:
    - name: Install Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    - name: Install
      shell: bash
      run: |
          echo "::group::Install"
          bun i palabra typos.ai -g --no-save
          palabra i typos
          echo "::endgroup::"
    - name: Run typos
      shell: bash
      run: typos.ai
      env:
        TYPOS_AI_KEY: ${{ inputs.key }}
        TYPOS_AI_RUN: ${{ inputs.run }}
